### ISSUE TITLE
init 작업 수정할 것들

### ISSUE THREAD

**Issue by kpryu6** [Kakao-X-Goorm-DEEP-DIVE-course/voting_system#1]
### 💼 작업 설명
- DB 관련 models.py 코드 수정
- settings.py에 SECRET_KEY 환경변수로 따로 관리 필요 (.gitignore)

### ✅ To-do
- [ ] ORM 사용을 할 것이기 때문에 models.py의 pymysql 코드 삭제
- [ ] SECRET_KEY 환경변수로 따로 관리하기

**제가 작성한 이슈가 맞는 설명들인지 검토부탁드립니다.**

**Comment by badasskim** [comment]
네 맞슴다 !
제가 이리저리 해본다고 아마 정리가 잘 안 간 상태로 갔군뇨,,, 담부터 클리닝 싹 하고 세팅하겠습니다

**Comment by kpryu6** [comment]
> 네 맞슴다 ! 제가 이리저리 해본다고 아마 정리가 잘 안 간 상태로 갔군뇨,,, 담부터 클리닝 싹 하고 세팅하겠습니다

에이 이런 이슈들 올리려고 이슈 사용하는거니까요!! 현진님 잘못이 절대절대로 아닙니다잉
프로젝트 관한 생각들이나 헷갈리는 것들도 여기서 공유해요! 근데 이슈가 이렇게 사용하는게 맞나..ㅋㅋㅋ..
