### ISSUE TITLE
백엔드 서비스 파트

### ISSUE THREAD

**Issue by kpryu6** [Kakao-X-Goorm-DEEP-DIVE-course/voting_system#2]
### 💼 작업 설명
MSA 핵심이 각 서비스가 독립적으로 배포되고 확장되는 거여서, 각 서비스를 다른 프로젝트로 분리하는 것이 이상적으로 보여요! 현재 프로젝트에서 많은 서비스를 다루지는 않지만 한 프로젝트에서 많은 앱을 다루면, 문제가 생길 시 프로젝트 전체가 날라갈 수(?) 있으므로 vote 프로젝트와 post 프로젝트를 별도의 Django 프로젝트로 따로 나누어서 진행하는 것이 좋아보입니다. @tkddk0108 

### ✅ To-do

- [ ] 게시물 서비스 프로젝트
- [ ] 투표 서비스 프로젝트
**따로 나누어서 진행!**

**Comment by tkddk0108** [comment]
Got it Thanks :)
